apiVersion: v1
kind: Pod
metadata:
  labels:
    run: efk-app
  name: efk-app
  namespace: default
spec:
  containers:
  - image: yoonkwon23/efk-docker:v1.0
    imagePullPolicy: IfNotPresent
    name: efk-app
    resources: {}
  restartPolicy: Always
